@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.pulsar.broker.service.ServerCnx#execute(Runnable)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.pulsar.broker.service.ServerCnx",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_523310109 { 
   	label=pulsar
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1014604199 { 
   	label=PulsarDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   PulsarDecoder1070348832XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="PulsarDecoder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1348467880 { 
   	label=NonPersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   NonPersistentTopic442146095XXXcheckGC0[
	label="+ checkGC()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXclose64711720[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

&#10;  Close this topic - close all producers and subscriptions associated with this topic.&#10; &#10;  @param closeWithoutWaitingClientDisconnect don't wait for client disconnect and forcefully close managed-ledger&#10;  @return Completable future indicating completion of close operation&#10; "
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXdelete0[
	label="+ delete()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXdeleteForcefully0[
	label="+ deleteForcefully()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

&#10;  Forcefully close all producers/consumers/replicators and deletes the topic.&#10; &#10;  @return&#10; "
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXonPoliciesUpdate611538288[
	label="+ onPoliciesUpdate()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXpublishMessage991694241[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1388282347 { 
   	label=ProxyBackendHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyBackendHandler828483243XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyBackendHandler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1660348955 { 
   	label=Producer
	labeljust=l
	fillcolor=white
	style=filled
   
   Producer1718290011XXXcheckAndStartPublish1302195195[
	label="+ checkAndStartPublish()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXcheckEncryption0[
	label="+ checkEncryption()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXcheckPermissionsAsync0[
	label="+ checkPermissionsAsync()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXdisconnect0[
	label="+ disconnect()"
	style=filled
	fillcolor=white
	tooltip="Producer

&#10;  It closes the producer from server-side and sends command to client to disconnect producer from existing&#10;  connection without closing that connection.&#10; &#10;  @return Completable future indicating completion of producer close&#10; "
	fontcolor=darkgreen
];

Producer1718290011XXXpublishMessage1309573701[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXpublishMessage1717589301[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXpublishTxnMessage617694510[
	label="+ publishTxnMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1842205426 { 
   	label=NonPersistentTopics
	labeljust=l
	fillcolor=white
	style=filled
   
   NonPersistentTopics620988780XXXunloadTopic1197121539[
	label="+ unloadTopic()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopics

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1945957077 { 
   	label=PersistentTopics
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentTopics620988780XXXunloadTopic1197121539[
	label="+ unloadTopic()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopics

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1975659038 { 
   	label=MessagePublishContext
	labeljust=l
	fillcolor=white
	style=filled
   
   MessagePublishContext1660348955XXXcompleted1453117839[
	label="+ completed()"
	style=filled
	fillcolor=white
	tooltip="MessagePublishContext

&#10;  Executed from managed ledger thread when the message is persisted.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2016466244 { 
   	label=Topics
	labeljust=l
	fillcolor=white
	style=filled
   
   Topics763407854XXXproduceOnNonPersistentTopic514140058[
	label="+ produceOnNonPersistentTopic()"
	style=filled
	fillcolor=white
	tooltip="Topics

null"
	fontcolor=darkgreen
];

Topics763407854XXXproduceOnNonPersistentTopicPartition957727127[
	label="+ produceOnNonPersistentTopicPartition()"
	style=filled
	fillcolor=white
	tooltip="Topics

null"
	fontcolor=darkgreen
];

Topics763407854XXXproduceOnPersistentTopic514140058[
	label="+ produceOnPersistentTopic()"
	style=filled
	fillcolor=white
	tooltip="Topics

null"
	fontcolor=darkgreen
];

Topics763407854XXXproduceOnPersistentTopicPartition957727127[
	label="+ produceOnPersistentTopicPartition()"
	style=filled
	fillcolor=white
	tooltip="Topics

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_359057108 { 
   	label=PersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentTopic1101090806XXXaddComplete1491430175[
	label="+ addComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXaddFailed715383354[
	label="+ addFailed()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXcheckGC0[
	label="+ checkGC()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXcheckReplication0[
	label="+ checkReplication()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXclose0[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXclose64711720[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Close this topic - close all producers and subscriptions associated with this topic.&#10; &#10;  @param closeWithoutWaitingClientDisconnect don't wait for client disconnect and forcefully close managed-ledger&#10;  @return Completable future indicating completion of close operation&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXdelete0[
	label="+ delete()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Delete the managed ledger associated with this topic.&#10; &#10;  @return Completable future indicating completion of delete operation Completed exceptionally with:&#10;  IllegalStateException if topic is still active ManagedLedgerException if ledger delete operation fails&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXdeleteForcefully0[
	label="+ deleteForcefully()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Forcefully close all producers/consumers/replicators and deletes the topic. this function is used when local&#10;  cluster is removed from global-namespace replication list. Because broker doesn't allow lookup if local cluster&#10;  is not part of replication cluster list.&#10; &#10;  @return&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXonPoliciesUpdate611538288[
	label="+ onPoliciesUpdate()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXpublishMessage991694241[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXpublishTxnMessage483951322[
	label="+ publishTxnMessage()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Publish Transaction message to this Topic's TransactionBuffer.&#10; &#10;  @param txnID Transaction Id&#10;  @param headersAndPayload Message data&#10;  @param publishContextPublish context&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_56109951 { 
   	label=BacklogQuotaManager
	labeljust=l
	fillcolor=white
	style=filled
   
   BacklogQuotaManager1718290011XXXhandleExceededBacklogQuota1796186035[
	label="+ handleExceededBacklogQuota()"
	style=filled
	fillcolor=white
	tooltip="BacklogQuotaManager

&#10;  Handle exceeded size backlog by using policies set in the zookeeper for given topic.&#10; &#10;  @param persistentTopic Topic on which backlog has been exceeded&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_704824873 { 
   	label=BrokerService
	labeljust=l
	fillcolor=white
	style=filled
   
   BrokerService1718290011XXXdeleteTopic1344699505[
	label="+ deleteTopic()"
	style=filled
	fillcolor=white
	tooltip="BrokerService

null"
	fontcolor=darkgreen
];

BrokerService1718290011XXXmonitorBacklogQuota0[
	label="+ monitorBacklogQuota()"
	style=filled
	fillcolor=white
	tooltip="BrokerService

null"
	fontcolor=darkgreen
];

BrokerService1718290011XXXunloadServiceUnit2087797420[
	label="+ unloadServiceUnit()"
	style=filled
	fillcolor=white
	tooltip="BrokerService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_822724435 { 
   	label=ReplicatedSubscriptionsController
	labeljust=l
	fillcolor=white
	style=filled
   
   ReplicatedSubscriptionsController1101090806XXXlocalSubscriptionUpdated723369190[
	label="+ localSubscriptionUpdated()"
	style=filled
	fillcolor=white
	tooltip="ReplicatedSubscriptionsController

null"
	fontcolor=darkgreen
];

ReplicatedSubscriptionsController1101090806XXXreceivedReplicatedSubscriptionMarker516434395[
	label="+ receivedReplicatedSubscriptionMarker()"
	style=filled
	fillcolor=white
	tooltip="ReplicatedSubscriptionsController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_923169591 { 
   	label=ServerCnx
	labeljust=l
	fillcolor=white
	style=filled
   
   ServerCnx1718290011XXXctx0[
	label="+ ctx()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	fontcolor=darkgreen
];

ServerCnx1718290011XXXexecute894056253[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_961973220 { 
   	label=ProxyConnection
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyConnection79518146XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyConnection

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_91979707 { 
   	label=bookkeeper
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_569476203 { 
   	label=OpAddEntry
	labeljust=l
	fillcolor=white
	style=filled
   
   OpAddEntry997059435XXXcloseComplete394845177[
	label="+ closeComplete()"
	style=filled
	fillcolor=white
	tooltip="OpAddEntry

null"
	fontcolor=darkgreen
];

OpAddEntry997059435XXXfailed469076839[
	label="+ failed()"
	style=filled
	fillcolor=white
	tooltip="OpAddEntry

null"
	fontcolor=darkgreen
];

OpAddEntry997059435XXXsafeRun0[
	label="+ safeRun()"
	style=filled
	fillcolor=white
	tooltip="OpAddEntry

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
BacklogQuotaManager1718290011XXXhandleExceededBacklogQuota1796186035 -> Producer1718290011XXXdisconnect0;
BrokerService1718290011XXXdeleteTopic1344699505 -> NonPersistentTopic442146095XXXdelete0;
BrokerService1718290011XXXdeleteTopic1344699505 -> NonPersistentTopic442146095XXXdeleteForcefully0;
BrokerService1718290011XXXmonitorBacklogQuota0 -> BacklogQuotaManager1718290011XXXhandleExceededBacklogQuota1796186035;
BrokerService1718290011XXXunloadServiceUnit2087797420 -> NonPersistentTopic442146095XXXclose64711720;
MessagePublishContext1660348955XXXcompleted1453117839 -> ServerCnx1718290011XXXexecute894056253;
NonPersistentTopic442146095XXXcheckGC0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXclose64711720 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXdelete0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXdeleteForcefully0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXonPoliciesUpdate611538288 -> Producer1718290011XXXcheckPermissionsAsync0;
NonPersistentTopic442146095XXXpublishMessage991694241 -> MessagePublishContext1660348955XXXcompleted1453117839;
NonPersistentTopics620988779XXXunloadTopic1592718600 -> NonPersistentTopic442146095XXXclose64711720;
NonPersistentTopics620988780XXXunloadTopic1197121539 -> NonPersistentTopic442146095XXXclose64711720;
OpAddEntry997059435XXXcloseComplete394845177 -> PersistentTopic1101090806XXXaddComplete1491430175;
OpAddEntry997059435XXXfailed469076839 -> PersistentTopic1101090806XXXaddFailed715383354;
OpAddEntry997059435XXXsafeRun0 -> PersistentTopic1101090806XXXaddComplete1491430175;
PersistentTopic1101090806XXXaddComplete1491430175 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXaddFailed715383354 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXaddFailed715383354 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXcheckGC0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXcheckReplication0 -> PersistentTopic1101090806XXXdeleteForcefully0;
PersistentTopic1101090806XXXclose0 -> PersistentTopic1101090806XXXclose64711720;
PersistentTopic1101090806XXXclose64711720 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXdelete0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXdeleteForcefully0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXonPoliciesUpdate611538288 -> Producer1718290011XXXcheckPermissionsAsync0;
PersistentTopic1101090806XXXpublishMessage991694241 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXpublishTxnMessage483951322 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXpublishTxnMessage483951322 -> PersistentTopic1101090806XXXaddFailed715383354;
PersistentTopics620988779XXXunloadTopic1592718600 -> NonPersistentTopic442146095XXXclose64711720;
PersistentTopics620988780XXXunloadTopic1197121539 -> NonPersistentTopic442146095XXXclose64711720;
Producer1718290011XXXcheckAndStartPublish1302195195 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXcheckEncryption0 -> Producer1718290011XXXdisconnect0;
Producer1718290011XXXcheckPermissionsAsync0 -> Producer1718290011XXXdisconnect0;
Producer1718290011XXXdisconnect0 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXpublishMessage1309573701 -> NonPersistentTopic442146095XXXpublishMessage991694241;
Producer1718290011XXXpublishMessage1309573701 -> Producer1718290011XXXcheckAndStartPublish1302195195;
Producer1718290011XXXpublishMessage1717589301 -> NonPersistentTopic442146095XXXpublishMessage991694241;
Producer1718290011XXXpublishMessage1717589301 -> Producer1718290011XXXcheckAndStartPublish1302195195;
Producer1718290011XXXpublishMessage1717589301 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXpublishTxnMessage617694510 -> Producer1718290011XXXcheckAndStartPublish1302195195;
ProxyBackendHandler828483243XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
ProxyConnection79518146XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> Producer1718290011XXXpublishMessage1717589301;
ReplicatedSubscriptionsController1101090806XXXlocalSubscriptionUpdated723369190 -> PersistentTopic1101090806XXXpublishMessage991694241;
ReplicatedSubscriptionsController1101090806XXXreceivedReplicatedSubscriptionMarker516434395 -> PersistentTopic1101090806XXXpublishMessage991694241;
ServerCnx1718290011XXXexecute894056253 -> ServerCnx1718290011XXXctx0;
Topics763407854XXXproduceOnNonPersistentTopic514140058 -> NonPersistentTopic442146095XXXpublishMessage991694241;
Topics763407854XXXproduceOnNonPersistentTopicPartition957727127 -> NonPersistentTopic442146095XXXpublishMessage991694241;
Topics763407854XXXproduceOnPersistentTopic514140058 -> NonPersistentTopic442146095XXXpublishMessage991694241;
Topics763407854XXXproduceOnPersistentTopicPartition957727127 -> NonPersistentTopic442146095XXXpublishMessage991694241;
    
}
@enduml