@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.pulsar.broker.service.ServerCnx#isActive()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.pulsar.broker.service.ServerCnx",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_523310109 { 
   	label=pulsar
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1014604199 { 
   	label=PulsarDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   PulsarDecoder1070348832XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="PulsarDecoder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1301977158 { 
   	label=AbstractTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractTopic1718290011XXXaddProducer1295200911[
	label="+ addProducer()"
	style=filled
	fillcolor=white
	tooltip="AbstractTopic

&#10;  Tries to add a producer to the topic. Several validations will be performed.&#10; &#10;  @param producer&#10;  @param producerQueuedFuture&#10; a future that will be triggered if the producer is being queued up prior of getting established&#10;  @return the \"topic epoch\" if there is one or empty&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1348467880 { 
   	label=NonPersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   NonPersistentTopic442146095XXXsubscribe2062160637[
	label="+ subscribe()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXsubscribe8945646[
	label="+ subscribe()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

&#10;  Subscribe a topic.&#10;  @param option&#10;  @return&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1388282347 { 
   	label=ProxyBackendHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyBackendHandler828483243XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyBackendHandler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1660348955 { 
   	label=Producer
	labeljust=l
	fillcolor=white
	style=filled
   
   Producer1718290011XXXclose64711720[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="Producer

&#10;  Close the producer immediately if: a. the connection is dropped b. it's a graceful close and no pending publish&#10;  acks are left else wait for pending publish acks&#10; &#10;  @return completable future indicate completion of close&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_359057108 { 
   	label=PersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentTopic1101090806XXXaddProducer1295200911[
	label="+ addProducer()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Tries to add a producer to the topic. Several validations will be performed.&#10; &#10;  @param producer&#10;  @param producerQueuedFuture&#10; a future that will be triggered if the producer is being queued up prior of getting established&#10;  @return the \"topic epoch\" if there is one or empty&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXsubscribe2062160637[
	label="+ subscribe()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXsubscribe8945646[
	label="+ subscribe()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Subscribe a topic.&#10;  @param option&#10;  @return&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_923169591 { 
   	label=ServerCnx
	labeljust=l
	fillcolor=white
	style=filled
   
   ServerCnx1718290011XXXisActive0[
	label="+ isActive()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_961973220 { 
   	label=ProxyConnection
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyConnection79518146XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyConnection

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AbstractTopic1718290011XXXaddProducer1295200911 -> Producer1718290011XXXclose64711720;
NonPersistentTopic442146095XXXsubscribe2062160637 -> ServerCnx1718290011XXXisActive0;
NonPersistentTopic442146095XXXsubscribe8945646 -> ServerCnx1718290011XXXisActive0;
PersistentTopic1101090806XXXaddProducer1295200911 -> AbstractTopic1718290011XXXaddProducer1295200911;
PersistentTopic1101090806XXXsubscribe2062160637 -> ServerCnx1718290011XXXisActive0;
PersistentTopic1101090806XXXsubscribe8945646 -> ServerCnx1718290011XXXisActive0;
Producer1718290011XXXclose64711720 -> ServerCnx1718290011XXXisActive0;
ProxyBackendHandler828483243XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
ProxyConnection79518146XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> NonPersistentTopic442146095XXXsubscribe8945646;
PulsarDecoder1070348832XXXchannelRead995363995 -> Producer1718290011XXXclose64711720;
PulsarDecoder1070348832XXXchannelRead995363995 -> ProxyBackendHandler828483243XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> ProxyConnection79518146XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> ServerCnx1718290011XXXisActive0;
    
}
@enduml