@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.pulsar.broker.service.ServerCnx#ctx()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.pulsar.broker.service.ServerCnx",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_523310109 { 
   	label=pulsar
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1014604199 { 
   	label=PulsarDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   PulsarDecoder1070348832XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="PulsarDecoder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1224357303 { 
   	label=Consumer
	labeljust=l
	fillcolor=white
	style=filled
   
   Consumer1718290011XXXdoUnsubscribe3327612[
	label="+ doUnsubscribe()"
	style=filled
	fillcolor=white
	tooltip="Consumer

null"
	fontcolor=darkgreen
];

Consumer1718290011XXXreachedEndOfTopic0[
	label="+ reachedEndOfTopic()"
	style=filled
	fillcolor=white
	tooltip="Consumer

null"
	fontcolor=darkgreen
];

Consumer1718290011XXXsendMessages1093529996[
	label="+ sendMessages()"
	style=filled
	fillcolor=white
	tooltip="Consumer

&#10;  Dispatch a list of entries to the consumer. \<br/\>&#10;  \<b\>It is also responsible to release entries data and recycle entries object.\</b\>&#10; &#10;  @return a SendMessageInfo object that contains the detail of what was sent to consumer&#10; "
	fontcolor=darkgreen
];

Consumer1718290011XXXsendMessages1436037244[
	label="+ sendMessages()"
	style=filled
	fillcolor=white
	tooltip="Consumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1348467880 { 
   	label=NonPersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   NonPersistentTopic442146095XXXcheckGC0[
	label="+ checkGC()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXclose64711720[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

&#10;  Close this topic - close all producers and subscriptions associated with this topic.&#10; &#10;  @param closeWithoutWaitingClientDisconnect don't wait for client disconnect and forcefully close managed-ledger&#10;  @return Completable future indicating completion of close operation&#10; "
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXdelete0[
	label="+ delete()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXdeleteForcefully0[
	label="+ deleteForcefully()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

&#10;  Forcefully close all producers/consumers/replicators and deletes the topic.&#10; &#10;  @return&#10; "
	fontcolor=darkgreen
];

NonPersistentTopic442146095XXXpublishMessage991694241[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="NonPersistentTopic

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1388282347 { 
   	label=ProxyBackendHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyBackendHandler828483243XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyBackendHandler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1464767387 { 
   	label=CompactedTopicImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   CompactedTopicImpl435643328XXXasyncReadEntriesOrWait2035996903[
	label="+ asyncReadEntriesOrWait()"
	style=filled
	fillcolor=white
	tooltip="CompactedTopicImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1579858382 { 
   	label=PersistentStreamingDispatcherSingleActiveConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXinternalReadEntryComplete274903556[
	label="+ internalReadEntryComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentStreamingDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];

PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXreadEntryComplete274903556[
	label="+ readEntryComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentStreamingDispatcherSingleActiveConsumer

&#10;  {@inheritDoc}&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1580024560 { 
   	label=PulsarCommandSenderImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624[
	label="+ sendActiveConsumerChange()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendConnectedResponse515322732[
	label="+ sendConnectedResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendError1409089306[
	label="+ sendError()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendErrorResponse1409089306[
	label="+ sendErrorResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendGetOrCreateSchemaErrorResponse1409089306[
	label="+ sendGetOrCreateSchemaErrorResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendGetOrCreateSchemaResponse955429095[
	label="+ sendGetOrCreateSchemaResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendGetSchemaErrorResponse1409089306[
	label="+ sendGetSchemaErrorResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendGetSchemaResponse1552850436[
	label="+ sendGetSchemaResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendGetTopicsOfNamespaceResponse1537759199[
	label="+ sendGetTopicsOfNamespaceResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendLookupResponse1828102398[
	label="+ sendLookupResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendLookupResponse1848351622[
	label="+ sendLookupResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendMessagesToConsumer1208411256[
	label="+ sendMessagesToConsumer()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendPartitionMetadataResponse1204774241[
	label="+ sendPartitionMetadataResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendPartitionMetadataResponse1848351622[
	label="+ sendPartitionMetadataResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendProducerSuccessResponse480552168[
	label="+ sendProducerSuccessResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendProducerSuccessResponse947897250[
	label="+ sendProducerSuccessResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendReachedEndOfTopic3327612[
	label="+ sendReachedEndOfTopic()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendSendError714559530[
	label="+ sendSendError()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendSendReceiptResponse61252156[
	label="+ sendSendReceiptResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendSuccess3327612[
	label="+ sendSuccess()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendSuccessResponse3327612[
	label="+ sendSuccessResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendTcClientConnectResponse1409089306[
	label="+ sendTcClientConnectResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];

PulsarCommandSenderImpl1718290011XXXsendTcClientConnectResponse3327612[
	label="+ sendTcClientConnectResponse()"
	style=filled
	fillcolor=white
	tooltip="PulsarCommandSenderImpl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1660348955 { 
   	label=Producer
	labeljust=l
	fillcolor=white
	style=filled
   
   Producer1718290011XXXcheckAndStartPublish1302195195[
	label="+ checkAndStartPublish()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXcheckEncryption0[
	label="+ checkEncryption()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXcheckPermissionsAsync0[
	label="+ checkPermissionsAsync()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXdisconnect0[
	label="+ disconnect()"
	style=filled
	fillcolor=white
	tooltip="Producer

&#10;  It closes the producer from server-side and sends command to client to disconnect producer from existing&#10;  connection without closing that connection.&#10; &#10;  @return Completable future indicating completion of producer close&#10; "
	fontcolor=darkgreen
];

Producer1718290011XXXpublishMessage1309573701[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXpublishMessage1717589301[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];

Producer1718290011XXXpublishTxnMessage617694510[
	label="+ publishTxnMessage()"
	style=filled
	fillcolor=white
	tooltip="Producer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1975659038 { 
   	label=MessagePublishContext
	labeljust=l
	fillcolor=white
	style=filled
   
   MessagePublishContext1660348955XXXcompleted1453117839[
	label="+ completed()"
	style=filled
	fillcolor=white
	tooltip="MessagePublishContext

&#10;  Executed from managed ledger thread when the message is persisted.&#10; "
	fontcolor=darkgreen
];

MessagePublishContext1660348955XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="MessagePublishContext

&#10;  Executed from I/O thread when sending receipt back to client.&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_2022822952 { 
   	label=PersistentSubscription
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentSubscription1101090806XXXaddConsumer503125994[
	label="+ addConsumer()"
	style=filled
	fillcolor=white
	tooltip="PersistentSubscription

null"
	fontcolor=darkgreen
];

PersistentSubscription1101090806XXXremoveConsumer1221979358[
	label="+ removeConsumer()"
	style=filled
	fillcolor=white
	tooltip="PersistentSubscription

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_300981562 { 
   	label=PersistentDispatcherSingleActiveConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentDispatcherSingleActiveConsumer1101090806XXXinternalReadEntriesComplete1160535363[
	label="+ internalReadEntriesComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];

PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesComplete1160535363[
	label="+ readEntriesComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];

PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354[
	label="+ readEntriesFailed()"
	style=filled
	fillcolor=white
	tooltip="PersistentDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_359057108 { 
   	label=PersistentTopic
	labeljust=l
	fillcolor=white
	style=filled
   
   PersistentTopic1101090806XXXaddComplete1491430175[
	label="+ addComplete()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXaddFailed715383354[
	label="+ addFailed()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXcheckGC0[
	label="+ checkGC()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXclose64711720[
	label="+ close()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Close this topic - close all producers and subscriptions associated with this topic.&#10; &#10;  @param closeWithoutWaitingClientDisconnect don't wait for client disconnect and forcefully close managed-ledger&#10;  @return Completable future indicating completion of close operation&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXdelete0[
	label="+ delete()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Delete the managed ledger associated with this topic.&#10; &#10;  @return Completable future indicating completion of delete operation Completed exceptionally with:&#10;  IllegalStateException if topic is still active ManagedLedgerException if ledger delete operation fails&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXdeleteForcefully0[
	label="+ deleteForcefully()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Forcefully close all producers/consumers/replicators and deletes the topic. this function is used when local&#10;  cluster is removed from global-namespace replication list. Because broker doesn't allow lookup if local cluster&#10;  is not part of replication cluster list.&#10; &#10;  @return&#10; "
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXpublishMessage991694241[
	label="+ publishMessage()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

null"
	fontcolor=darkgreen
];

PersistentTopic1101090806XXXpublishTxnMessage483951322[
	label="+ publishTxnMessage()"
	style=filled
	fillcolor=white
	tooltip="PersistentTopic

&#10;  Publish Transaction message to this Topic's TransactionBuffer.&#10; &#10;  @param txnID Transaction Id&#10;  @param headersAndPayload Message data&#10;  @param publishContextPublish context&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_56109951 { 
   	label=BacklogQuotaManager
	labeljust=l
	fillcolor=white
	style=filled
   
   BacklogQuotaManager1718290011XXXhandleExceededBacklogQuota1796186035[
	label="+ handleExceededBacklogQuota()"
	style=filled
	fillcolor=white
	tooltip="BacklogQuotaManager

&#10;  Handle exceeded size backlog by using policies set in the zookeeper for given topic.&#10; &#10;  @param persistentTopic Topic on which backlog has been exceeded&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_923169591 { 
   	label=ServerCnx
	labeljust=l
	fillcolor=white
	style=filled
   
   ServerCnx1718290011XXXctx0[
	label="+ ctx()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	penwidth=4
	fontcolor=darkgreen
];

ServerCnx1718290011XXXexecute894056253[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_939167584 { 
   	label=AbstractDispatcherSingleActiveConsumer
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractDispatcherSingleActiveConsumer1718290011XXXaddConsumer503125994[
	label="+ addConsumer()"
	style=filled
	fillcolor=white
	tooltip="AbstractDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];

AbstractDispatcherSingleActiveConsumer1718290011XXXremoveConsumer503125994[
	label="+ removeConsumer()"
	style=filled
	fillcolor=white
	tooltip="AbstractDispatcherSingleActiveConsumer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_961973220 { 
   	label=ProxyConnection
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyConnection79518146XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyConnection

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_91979707 { 
   	label=bookkeeper
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1810717276 { 
   	label=ManagedCursorImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   ManagedCursorImpl997059435XXXasyncReadEntries1425431748[
	label="+ asyncReadEntries()"
	style=filled
	fillcolor=white
	tooltip="ManagedCursorImpl

&#10;  Asynchronously read entries from the ManagedLedger.&#10; &#10;  @param numberOfEntriesToRead maximum number of entries to return&#10;  @param maxSizeBytes max size in bytes of the entries to return&#10;  @param callback callback object&#10;  @param ctx opaque context&#10;  @param maxPosition max position can read&#10; "
	fontcolor=darkgreen
];

ManagedCursorImpl997059435XXXasyncReadEntriesOrWait1425431748[
	label="+ asyncReadEntriesOrWait()"
	style=filled
	fillcolor=white
	tooltip="ManagedCursorImpl

&#10;  Asynchronously read entries from the ManagedLedger, up to the specified number and size.&#10; &#10;  \<p/\>If no entries are available, the callback will not be triggered. Instead it will be registered to wait until&#10;  a new message will be persisted into the managed ledger&#10; &#10;  @see #readEntriesOrWait(int, long)&#10;  @param maxEntries&#10; maximum number of entries to return&#10;  @param maxSizeBytes&#10; max size in bytes of the entries to return&#10;  @param callback&#10; callback object&#10;  @param ctx&#10; opaque context&#10;  @param maxPosition&#10; max position can read&#10; "
	fontcolor=darkgreen
];

ManagedCursorImpl997059435XXXasyncReplayEntries1799849047[
	label="+ asyncReplayEntries()"
	style=filled
	fillcolor=white
	tooltip="ManagedCursorImpl

&#10;  Read the specified set of positions from ManagedLedger.&#10; &#10;  @param positions&#10; set of positions to read&#10;  @param callback&#10; callback object returning the list of entries&#10;  @param ctx&#10; opaque context&#10;  @param sortEntries&#10; callback with sorted entry list.&#10;  @return skipped positions&#10;  set of positions which are already deleted/acknowledged and skipped while replaying them&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_241557257 { 
   	label=EntryCacheImpl
	labeljust=l
	fillcolor=white
	style=filled
   
   EntryCacheImpl997059435XXXasyncReadEntry2057241960[
	label="+ asyncReadEntry()"
	style=filled
	fillcolor=white
	tooltip="EntryCacheImpl

&#10;  Read entries from the cache or from bookkeeper.&#10; &#10;  \<p/\>Get the entry data either from cache or bookkeeper and mixes up the results in a single list.&#10; &#10;  @param lh&#10; the ledger handle&#10;  @param firstEntry&#10; the first entry to read (inclusive)&#10;  @param lastEntry&#10; the last entry to read (inclusive)&#10;  @param isSlowestReader&#10; whether the reader cursor is the most far behind in the stream&#10;  @param callback&#10; the callback object that will be notified when read is done&#10;  @param ctx&#10; the context object&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_258299998 { 
   	label=OpReadEntry
	labeljust=l
	fillcolor=white
	style=filled
   
   OpReadEntry997059435XXXreadEntriesFailed715383354[
	label="+ readEntriesFailed()"
	style=filled
	fillcolor=white
	tooltip="OpReadEntry

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_277434614 { 
   	label=EntryCacheDisabled
	labeljust=l
	fillcolor=white
	style=filled
   
   EntryCacheDisabled1071447588XXXasyncReadEntry2057241960[
	label="+ asyncReadEntry()"
	style=filled
	fillcolor=white
	tooltip="EntryCacheDisabled

&#10;  Read entries from the cache or from bookkeeper.&#10; &#10;  \<p/\>Get the entry data either from cache or bookkeeper and mixes up the results in a single list.&#10; &#10;  @param lh&#10; the ledger handle&#10;  @param firstEntry&#10; the first entry to read (inclusive)&#10;  @param lastEntry&#10; the last entry to read (inclusive)&#10;  @param isSlowestReader&#10; whether the reader cursor is the most far behind in the stream&#10;  @param callback&#10; the callback object that will be notified when read is done&#10;  @param ctx&#10; the context object&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_936928591 { 
   	label=ReadEntryCallbackWrapper
	labeljust=l
	fillcolor=white
	style=filled
   
   ReadEntryCallbackWrapper2079345937XXXreadEntriesFailed715383354[
	label="+ readEntriesFailed()"
	style=filled
	fillcolor=white
	tooltip="ReadEntryCallbackWrapper

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AbstractDispatcherSingleActiveConsumer1718290011XXXaddConsumer503125994 -> PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624;
AbstractDispatcherSingleActiveConsumer1718290011XXXremoveConsumer503125994 -> PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624;
BacklogQuotaManager1718290011XXXhandleExceededBacklogQuota1796186035 -> Producer1718290011XXXdisconnect0;
CompactedTopicImpl435643328XXXasyncReadEntriesOrWait2035996903 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
Consumer1718290011XXXdoUnsubscribe3327612 -> PulsarCommandSenderImpl1718290011XXXsendError1409089306;
Consumer1718290011XXXdoUnsubscribe3327612 -> PulsarCommandSenderImpl1718290011XXXsendSuccess3327612;
Consumer1718290011XXXreachedEndOfTopic0 -> PulsarCommandSenderImpl1718290011XXXsendReachedEndOfTopic3327612;
Consumer1718290011XXXsendMessages1093529996 -> PulsarCommandSenderImpl1718290011XXXsendMessagesToConsumer1208411256;
Consumer1718290011XXXsendMessages1436037244 -> Consumer1718290011XXXsendMessages1093529996;
EntryCacheDisabled1071447588XXXasyncReadEntry2057241960 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
EntryCacheImpl997059435XXXasyncReadEntry2057241960 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
ManagedCursorImpl997059435XXXasyncReadEntries1425431748 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
ManagedCursorImpl997059435XXXasyncReadEntriesOrWait1425431748 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
ManagedCursorImpl997059435XXXasyncReplayEntries1799849047 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
MessagePublishContext1660348955XXXcompleted1453117839 -> PulsarCommandSenderImpl1718290011XXXsendSendError714559530;
MessagePublishContext1660348955XXXcompleted1453117839 -> ServerCnx1718290011XXXexecute894056253;
MessagePublishContext1660348955XXXrun0 -> PulsarCommandSenderImpl1718290011XXXsendSendReceiptResponse61252156;
NonPersistentTopic442146095XXXcheckGC0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXclose64711720 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXdelete0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXdeleteForcefully0 -> Producer1718290011XXXdisconnect0;
NonPersistentTopic442146095XXXpublishMessage991694241 -> MessagePublishContext1660348955XXXcompleted1453117839;
OpReadEntry997059435XXXreadEntriesFailed715383354 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
PersistentDispatcherSingleActiveConsumer1101090806XXXinternalReadEntriesComplete1160535363 -> Consumer1718290011XXXsendMessages1093529996;
PersistentDispatcherSingleActiveConsumer1101090806XXXinternalReadEntriesComplete1160535363 -> PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624;
PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesComplete1160535363 -> PersistentDispatcherSingleActiveConsumer1101090806XXXinternalReadEntriesComplete1160535363;
PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354 -> PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624;
PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXinternalReadEntryComplete274903556 -> Consumer1718290011XXXsendMessages1093529996;
PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXinternalReadEntryComplete274903556 -> PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624;
PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXreadEntryComplete274903556 -> PersistentStreamingDispatcherSingleActiveConsumer1101090806XXXinternalReadEntryComplete274903556;
PersistentSubscription1101090806XXXaddConsumer503125994 -> AbstractDispatcherSingleActiveConsumer1718290011XXXaddConsumer503125994;
PersistentSubscription1101090806XXXremoveConsumer1221979358 -> AbstractDispatcherSingleActiveConsumer1718290011XXXremoveConsumer503125994;
PersistentTopic1101090806XXXaddComplete1491430175 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXaddFailed715383354 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXaddFailed715383354 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXcheckGC0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXclose64711720 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXdelete0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXdeleteForcefully0 -> Producer1718290011XXXdisconnect0;
PersistentTopic1101090806XXXpublishMessage991694241 -> MessagePublishContext1660348955XXXcompleted1453117839;
PersistentTopic1101090806XXXpublishTxnMessage483951322 -> MessagePublishContext1660348955XXXcompleted1453117839;
Producer1718290011XXXcheckAndStartPublish1302195195 -> PulsarCommandSenderImpl1718290011XXXsendSendError714559530;
Producer1718290011XXXcheckAndStartPublish1302195195 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXcheckEncryption0 -> Producer1718290011XXXdisconnect0;
Producer1718290011XXXcheckPermissionsAsync0 -> Producer1718290011XXXdisconnect0;
Producer1718290011XXXdisconnect0 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXpublishMessage1309573701 -> Producer1718290011XXXcheckAndStartPublish1302195195;
Producer1718290011XXXpublishMessage1717589301 -> Producer1718290011XXXcheckAndStartPublish1302195195;
Producer1718290011XXXpublishMessage1717589301 -> PulsarCommandSenderImpl1718290011XXXsendSendError714559530;
Producer1718290011XXXpublishMessage1717589301 -> ServerCnx1718290011XXXexecute894056253;
Producer1718290011XXXpublishTxnMessage617694510 -> Producer1718290011XXXcheckAndStartPublish1302195195;
ProxyBackendHandler828483243XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
ProxyConnection79518146XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
PulsarCommandSenderImpl1718290011XXXsendActiveConsumerChange1260199624 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendConnectedResponse515322732 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendError1409089306 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendErrorResponse1409089306 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendGetOrCreateSchemaErrorResponse1409089306 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendGetOrCreateSchemaResponse955429095 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendGetSchemaErrorResponse1409089306 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendGetSchemaResponse1552850436 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendGetTopicsOfNamespaceResponse1537759199 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendLookupResponse1828102398 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendLookupResponse1848351622 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendMessagesToConsumer1208411256 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendPartitionMetadataResponse1204774241 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendPartitionMetadataResponse1848351622 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendProducerSuccessResponse480552168 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendProducerSuccessResponse947897250 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendReachedEndOfTopic3327612 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendSendError714559530 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendSendReceiptResponse61252156 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendSuccess3327612 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendSuccessResponse3327612 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendTcClientConnectResponse1409089306 -> ServerCnx1718290011XXXctx0;
PulsarCommandSenderImpl1718290011XXXsendTcClientConnectResponse3327612 -> PulsarCommandSenderImpl1718290011XXXsendTcClientConnectResponse1409089306;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendErrorResponse1409089306;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendGetOrCreateSchemaResponse955429095;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendGetSchemaResponse1552850436;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendPartitionMetadataResponse1848351622;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendSendReceiptResponse61252156;
PulsarDecoder1070348832XXXchannelRead995363995 -> PulsarCommandSenderImpl1718290011XXXsendSuccessResponse3327612;
ReadEntryCallbackWrapper2079345937XXXreadEntriesFailed715383354 -> PersistentDispatcherSingleActiveConsumer1101090806XXXreadEntriesFailed715383354;
ServerCnx1718290011XXXexecute894056253 -> ServerCnx1718290011XXXctx0;
    
}
@enduml