@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.apache.pulsar.broker.service.ServerCnx#getPrincipal()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.apache.pulsar.broker.service.ServerCnx",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1411517106 { 
   	label=apache
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_523310109 { 
   	label=pulsar
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1014604199 { 
   	label=PulsarDecoder
	labeljust=l
	fillcolor=white
	style=filled
   
   PulsarDecoder1070348832XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="PulsarDecoder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1388282347 { 
   	label=ProxyBackendHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyBackendHandler828483243XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyBackendHandler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_923169591 { 
   	label=ServerCnx
	labeljust=l
	fillcolor=white
	style=filled
   
   ServerCnx1718290011XXXgetPrincipal0[
	label="+ getPrincipal()"
	style=filled
	fillcolor=white
	tooltip="ServerCnx

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_961973220 { 
   	label=ProxyConnection
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyConnection79518146XXXchannelRead995363995[
	label="+ channelRead()"
	style=filled
	fillcolor=white
	tooltip="ProxyConnection

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ProxyBackendHandler828483243XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
ProxyConnection79518146XXXchannelRead995363995 -> PulsarDecoder1070348832XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> ProxyBackendHandler828483243XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> ProxyConnection79518146XXXchannelRead995363995;
PulsarDecoder1070348832XXXchannelRead995363995 -> ServerCnx1718290011XXXgetPrincipal0;
    
}
@enduml